language: node_js
node_js:
  - 12

before_install:
- export TZ=America/New_York

# services:
#   - postgresql

# before_script:
#   - yarn db-init-local

script:
  # - yarn db-migrate-down -c 999999
  # - yarn db-migrate-up
  - yarn test
  - yarn build
