language: node_js
node_js:
  - 12

env:
  - DB_CONFIG=test

before_install:
  - export TZ=America/New_York

services:
  - postgresql

# before_script:
#   - yarn db-init-local

jobs:
  include:
    - stage: Build
      script:
        - yarn build
    - stage: Client test
      script:
        - yarn workspace client run test
    - stage: Server test
      script:
        - yarn workspace server run test
        - yarn workspace test run test
