#!/bin/bash
ENVIRONMENT=$1
CONFIG_FILE=`pwd`/configs/$1.config

source $CONFIG_FILE

 psql -c "CREATE DATABASE $DATABASE"
 psql -c "CREATE ROLE $DB_USER WITH PASSWORD '$DB_PASSWORD'"
 psql -c "ALTER ROLE $DB_USER WITH LOGIN"
 psql -c "GRANT ALL PRIVILEGES ON DATABASE $DATABASE to $DB_USER"
